# Generated by Django 6.0.5 on 2026-05-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_seat_seatreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('rating', models.FloatField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='bookings.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='bookings.language')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='bookings_mo_title_2a4d58_idx'), models.Index(fields=['rating'], name='bookings_mo_rating_6b05b9_idx'), models.Index(fields=['release_date'], name='bookings_mo_release_e4d6c9_idx'), models.Index(fields=['is_active'], name='bookings_mo_is_acti_93de53_idx')],
            },
        ),
    ]
