# Generated by Django 6.0.5 on 2026-06-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_genre_language_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('total_seats', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(db_index=True, default=50000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='seatreservation',
            name='locked_until',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='seatreservation',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='LOCKED', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.theater'),
        ),
    ]
