# Generated by Django 6.0.5 on 2026-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_theater_booking_cancelled_at_alter_booking_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentevent',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
